version: '{build}'

image: Visual Studio 2013

environment:
  global:
    APPVEYOR_RDP_PASSWORD: 'FooBar01!'
  matrix:
    - TARGET_OS: Win7
    - TARGET_OS: Win8
    - TARGET_OS: Win8.1

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

  # On Win32, only build Debug to speed things up:
  exclude:
    - platform: Win32
      configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - ps: |
      cd $Env:APPVEYOR_BUILD_FOLDER
      New-Item -Type Directory build\cmake | Out-Null
      cd build\cmake

      cmake -A $Env:PLATFORM `
          "-DCMAKE_INSTALL_PREFIX=$Env:APPVEYOR_BUILD_FOLDER\build\install" `
          $Env:APPVEYOR_BUILD_FOLDER

      cmake --build . --target install --config $Env:CONFIGURATION
  - ps: |
      cd $Env:APPVEYOR_BUILD_FOLDER
      .\scripts\build.ps1 `
          -InstallDir .\build\install `
          -Configuration "$Env:TARGET_OS $Env:CONFIGURATION" `
          -Platform $Env:PLATFORM `
          -WDK wdk8.1update

after_build:
  - 7z.exe a "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%-%TARGET_OS%.zip" .\build\install\*
  - appveyor.exe PushArtifact "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%-%TARGET_OS%.zip"

for:
# Build Release on master only to speed things up:
- branches:
    except:
      - master
  configuration:
    - Debug

# Workers are 64-bit, can't load 32-bit drivers.
# https://github.com/appveyor/ci/issues/715
- matrix:
    only:
      - platform: x64
  install:
    - git submodule update --init --recursive
    - appveyor.exe AddMessage "Enabling self-signed drivers..."
    - bcdedit.exe /set TESTSIGNING ON
    - appveyor.exe AddMessage "Rebooting the worker..."
    - ps: Restart-Computer -Force
    - ps: Start-Sleep -s 10
    - appveyor.exe AddMessage "OK"
  test_script:
    - ps: .\scripts\test.ps1 -InstallDir build\install
